{
 "archived": false,
 "branch": "main",
 "conda-forge.yml": {},
 "feedstock_name": "up42-py",
 "hash_type": "sha256",
 "name": "up42-py",
 "outputs_names": {
  "__set__": true,
  "elements": [
   "up42-py"
  ]
 },
 "parsing_error": "make_graph: render error cond build error: RuntimeError('up42-py cannot depend on itself')\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 220, in parse_meta_yaml\n    return _run(use_orig_cbc_path=True)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 207, in _run\n    return _parse_meta_yaml_impl(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 312, in _parse_meta_yaml_impl\n    cfg_as_dict.update(conda_build.environ.get_dict(m=m))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 317, in get_dict\n    d.update(python_vars(m, prefix, escape_backslash))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 389, in python_vars\n    deps = [str(ms.name) for ms in metadata.ms_depends(build_or_host)]\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/metadata.py\", line 1518, in ms_depends\n    raise RuntimeError(\"%s cannot depend on itself\" % self.name())\nRuntimeError: up42-py cannot depend on itself\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 224, in parse_meta_yaml\n    return _run(use_orig_cbc_path=False)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 207, in _run\n    return _parse_meta_yaml_impl(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 312, in _parse_meta_yaml_impl\n    cfg_as_dict.update(conda_build.environ.get_dict(m=m))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 317, in get_dict\n    d.update(python_vars(m, prefix, escape_backslash))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 389, in python_vars\n    deps = [str(ms.name) for ms in metadata.ms_depends(build_or_host)]\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/metadata.py\", line 1518, in ms_depends\n    raise RuntimeError(\"%s cannot depend on itself\" % self.name())\nRuntimeError: up42-py cannot depend on itself\n\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 220, in parse_meta_yaml\n    return _run(use_orig_cbc_path=True)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 207, in _run\n    return _parse_meta_yaml_impl(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 312, in _parse_meta_yaml_impl\n    cfg_as_dict.update(conda_build.environ.get_dict(m=m))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 317, in get_dict\n    d.update(python_vars(m, prefix, escape_backslash))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 389, in python_vars\n    deps = [str(ms.name) for ms in metadata.ms_depends(build_or_host)]\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/metadata.py\", line 1518, in ms_depends\n    raise RuntimeError(\"%s cannot depend on itself\" % self.name())\nRuntimeError: up42-py cannot depend on itself\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 224, in parse_meta_yaml\n    return _run(use_orig_cbc_path=False)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 207, in _run\n    return _parse_meta_yaml_impl(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 312, in _parse_meta_yaml_impl\n    cfg_as_dict.update(conda_build.environ.get_dict(m=m))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 317, in get_dict\n    d.update(python_vars(m, prefix, escape_backslash))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 389, in python_vars\n    deps = [str(ms.name) for ms in metadata.ms_depends(build_or_host)]\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/metadata.py\", line 1518, in ms_depends\n    raise RuntimeError(\"%s cannot depend on itself\" % self.name())\nRuntimeError: up42-py cannot depend on itself\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/feedstock_parser.py\", line 248, in populate_feedstock_attributes\n    parse_meta_yaml(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 226, in parse_meta_yaml\n    raise RuntimeError(\nRuntimeError: cond build error: RuntimeError('up42-py cannot depend on itself')\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 220, in parse_meta_yaml\n    return _run(use_orig_cbc_path=True)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 207, in _run\n    return _parse_meta_yaml_impl(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 312, in _parse_meta_yaml_impl\n    cfg_as_dict.update(conda_build.environ.get_dict(m=m))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 317, in get_dict\n    d.update(python_vars(m, prefix, escape_backslash))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 389, in python_vars\n    deps = [str(ms.name) for ms in metadata.ms_depends(build_or_host)]\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/metadata.py\", line 1518, in ms_depends\n    raise RuntimeError(\"%s cannot depend on itself\" % self.name())\nRuntimeError: up42-py cannot depend on itself\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 224, in parse_meta_yaml\n    return _run(use_orig_cbc_path=False)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 207, in _run\n    return _parse_meta_yaml_impl(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 312, in _parse_meta_yaml_impl\n    cfg_as_dict.update(conda_build.environ.get_dict(m=m))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 317, in get_dict\n    d.update(python_vars(m, prefix, escape_backslash))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/environ.py\", line 389, in python_vars\n    deps = [str(ms.name) for ms in metadata.ms_depends(build_or_host)]\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/conda_build/metadata.py\", line 1518, in ms_depends\n    raise RuntimeError(\"%s cannot depend on itself\" % self.name())\nRuntimeError: up42-py cannot depend on itself\n\n",
 "platforms": [
  "linux_64"
 ],
 "pr_info": {
  "__lazy_json__": "pr_info/up42-py.json"
 },
 "raw_meta_yaml": "{% set name = \"up42-py\" %}\n{% set version = \"0.33.0\" %}\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/up42-py-{{ version }}.tar.gz\n  sha256: 89ddea14fec9f2ca3f53c0ee576a79ba29b876a9ae5da66ab991a0d393d62efe\n\nbuild:\n  noarch: python\n  script: {{ PYTHON }} -m pip install . -vv --no-deps\n  number: 0\n\nrequirements:\n  host:\n    - pip\n    - python >=3.8, <3.12\n    - poetry\n    - up42-py\n  run:\n    - branca\n    - folium\n    - geojson ==3.0.1\n    - geopandas ==0.13.2\n    - matplotlib-base\n    - python >=3.8, <3.12\n    - rasterio\n    - requests ==2.31.0\n    - requests-oauthlib\n    - tenacity ==8.2.2\n    - tqdm ==4.66.0\n    - pystac-client ==0.7.2\n    - shapely\n    - oauthlib\n    - pandas\n    - numpy\n    - pystac\n    - poetry\n\ntest:\n  imports:\n    - up42\n  commands:\n    - pip check\n  requires:\n    - pip\n\nabout:\n  home: https://github.com/up42/up42-py\n  summary: Python SDK for UP42\n  license: MIT\n  license_file: LICENSE\n  doc_url: https://sdk.up42.com\n  dev_url: https://github.com/up42/up42-py\n\nextra:\n  recipe-maintainers:\n    - andher1802\n    - seedlit\n",
 "strong_exports": false,
 "url": "https://pypi.io/packages/source/u/up42-py/up42-py-0.32.0.tar.gz",
 "version": "0.32.0",
 "version_pr_info": {
  "__lazy_json__": "version_pr_info/up42-py.json"
 }
}